require "core.options"
require "core.keymaps"
require "core.plugins"
require "core.nvim-cmp"
require "core.colorscheme"
require "core.nvim-tree"
require "core.telescope"
require "core.bufferline"
require "core.gitsigns"
require "core.lualine"
require "core.toggleterm"
require "core.project"
require "core.impatient"
require "core.indentline"
require "core.alpha"
require "core.whichkey"
require "core.comment"
require "core.treesitter"
require "core.autopairs"
require "core.dapui"
require "core.aerial-nvim"
require "core.fidget"
require "core.diffview-nvim"
require "lsp"
require "lsp.golang"
--[[ require "lsp.dap" ]]
--[[ require "tools" ]]
-- require "lsp.debug.dap-rust"
-- require "lsp.debug.dap-flutter"
